### ISSUE TITLE
Initial policy release is broken

### ISSUE THREAD

**Issue by kravciak** [kubewarden/namespace-label-propagator-policy#6]
### Current Behavior

- policy settings tab is not available
- policy module points to `yourorg` -> `ghcr.io/yourorg/policies/policy-name:v0.1.0`
- package has not been signed

![Screenshot from 2023-06-01 20-52-58](https://github.com/kubewarden/namespace-label-propagator-policy/assets/538604/8850ad37-4e91-4030-ac33-b3d17a3ee1b1)

**Comment by kravciak** [comment]
I can create a policy in UI now, but it still seems broken, when I start it in `Protect` mode I can't create pods:
```
> k run --image=nginx nginx
Error from server: admission webhook "clusterwide-nlp.kubewarden.admission" denied the request: Cannot get namespace data: Host error: Policy has not been granted access to Kubernetes v1/Namespace resources. The violation has been reported.
```

**Comment by flavio** [comment]
I suspect you have deployed the policy using the UI. Am I correct? If that's the case, please double check the `ClusterAdmissionPolicy` definition, I suspect the UI did **not** populate the [`contextAwareResources`](https://doc.crds.dev/github.com/kubewarden/kubewarden-controller/policies.kubewarden.io/ClusterAdmissionPolicy/v1@v1.6.0) section.

CC @jordojordo

**Comment by flavio** [comment]
I guess this is going to be fixed once https://github.com/kubewarden/ui/issues/388 is merged

**Comment by jordojordo** [comment]
@flavio is correct, the UI was not populating the `contextAwareResources` for the policy. This has been fixed with https://github.com/kubewarden/ui/issues/388, and a new release has be created ([`1.0.5`](https://github.com/kubewarden/ui/releases/tag/kubewarden-1.0.5)).

**Comment by viccuad** [comment]
thanks for 1.0.5! closing this then!
